name: Trigger auto deployment for deveasyops

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ Dev ]
    paths:
    - '**'
    - '.github/workflows/deveasyops-AutoDeployTrigger-778b40a4-1263-4869-90fd-3d6930487ac3.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: devimagens.azurecr.io
          username: ${{ secrets.DEVEASYOPS_REGISTRY_USERNAME }}
          password: ${{ secrets.DEVEASYOPS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: devimagens.azurecr.io/deveasyops:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEVEASYOPS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n deveasyops -g RG-DEV-OPS --server devimagens.azurecr.io --username  ${{ secrets.DEVEASYOPS_REGISTRY_USERNAME }} --password ${{ secrets.DEVEASYOPS_REGISTRY_PASSWORD }}
            az containerapp update -n deveasyops -g RG-DEV-OPS --image devimagens.azurecr.io/deveasyops:${{ github.sha }}
