name: Trigger auto deployment for siteeasyops

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/siteeasyops-AutoDeployTrigger-53e6cc75-52db-46a5-a026-2c5339442982.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: imagens.azurecr.io
          username: ${{ secrets.SITEEASYOPS_REGISTRY_USERNAME }}
          password: ${{ secrets.SITEEASYOPS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: imagens.azurecr.io/siteeasyops:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SITEEASYOPS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n siteeasyops -g RG-PRD-OPS --server imagens.azurecr.io --username  ${{ secrets.SITEEASYOPS_REGISTRY_USERNAME }} --password ${{ secrets.SITEEASYOPS_REGISTRY_PASSWORD }}
            az containerapp update -n siteeasyops -g RG-PRD-OPS --image imagens.azurecr.io/siteeasyops:${{ github.sha }}
